repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.1.0
    hooks:
      - id: reorder-python-imports
        args: ["--application-directories", "src"]
  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.3.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear"]
